name: Workflow de Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Verificar estrutura do repositório
        run: ls -l

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Garantir permissões para o diretório e arquivos
        run: chmod -R 755 .

      - name: Verificar diretório 'minha-api'
        run: ls -l ./minha-api

      - name: Navegar para o diretório e instalar dependências
        run: |
          cd minha-api
          npm install

      - name: Verificar se node_modules foi criado
        run: ls -l ./minha-api/node_modules

      - name: Garantir permissões dos binários
        run: chmod -R +x ./minha-api/node_modules/.bin/*

      - name: Executar testes
        run: npx jest
        working-directory: ./minha-api
