name: Workflow de Commit

on:
  push:
    branches:
      - main  # ou a branch que você está usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Navegar para o diretório correto e instalar dependências
        run: |
          cd minha-api
          npm install

      - name: Verificar se node_modules foi criado
        run: ls -l ./minha-api/node_modules
        working-directory: ./minha-api

      - name: Verificar se o Jest está presente
        run: ls -l ./minha-api/node_modules/.bin
        working-directory: ./minha-api

      - name: Garantir permissões dos binários
        run: chmod -R +x ./minha-api/node_modules/.bin/*
        working-directory: ./minha-api

      - name: Executar testes
        run: npx jest
        working-directory: ./minha-api
