name: Workflow de Commit

on:
  push:
    branches:
      - main  # ou a branch que você está usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Navegar entre diretórios 
        run: echo "Direcionando para o diretório ./minha-api"
        working-directory: ./minha-api  # Direciona para o diretório correto

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test
