name: Workflow de Commit

on:
  push:
    branches:
      - main  # ou a branch que você está usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Navegar para o diretório "minha-api"
        run: echo "Estamos no diretório raiz"
      
      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

          
      - name: Garantir permissões dos binários do Node.js
        run: chmod +x ./minha-api/node_modules/.bin/*
        working-directory: ./minha-api
        

      - name: Instalar dependências
        run: npm install
        working-directory: ./minha-api  # Direciona para o diretório correto

      - name: Executar testes
        run: npm test
        working-directory: ./minha-api  # Direciona para o diretório correto
