name: Workflow de Commit

on:
  push:
    branches:
      - main  # ou a branch que você está usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Navegar para o diretório "minha-api"
        run: echo "Estamos no diretório raiz"
      
      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install
        working-directory: ./minha-api

      - name: Garantir permissões dos binários do Node.js (se existir)
        run: |
          if [ -d "./minha-api/node_modules/.bin" ]; then
            chmod +x ./minha-api/node_modules/.bin/*
          fi
        working-directory: ./minha-api

      - name: Executar testes
        run: npx jest
        working-directory: ./minha-api
