name: Workflow de Commit

on:
  push:
    branches:
      - main  # ou a branch que você está usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install
        working-directory: ./minha-api

      - name: Garantir permissões para o Jest
        run: chmod +x ./minha-api/node_modules/.bin/jest
        working-directory: ./minha-api

      - name: Executar testes
        run: npx jest
        working-directory: ./minha-api
