name: CI on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Garantir permissões dos binários
        run: chmod -R +x ./minha-api/node_modules/.bin/*
      
      - name: Garantir permissões para o diretório e arquivos
        run: chmod -R 755 .

      - name: Executar testes e verificar cobertura
        run: |
          cd minha-api
          npm install
          npx jest --coverage
